stages:
  - check
  - deploy

check:
  stage: check
  image: rust
  cache:
    paths:
      - target
  script:
    - cargo build
    - cargo test

cache-nix-build:
  stage: deploy
  image: nixos/nix
  only:
    - master
    - gitlab-ci
  before_script:
    - nix-channel --list
    - nix-env -iA nixpkgs.git
    - nix-env -iA cachix -f https://cachix.org/api/v1/install
  script:
    - nix-build | cachix push jd91mzm2
