[package]
name = "git-subcopy"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
edition = "2018"

[dependencies]
git2 = "0.10.1"
base64 = "0.10.1"
dirs = "2.0.2"
structopt = "0.3.3"
anyhow = "1.0.11"
